name: realse-on-new-tag.yml
on:
  workflow_dispatch: # Démarrer manuellement
#  push:
#    tags:
#      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestEnv # Préciser l'environnement utilisé.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build solution
        run: dotnet build

      - name: Test solution
        run: dotnet test

      - name: Package application
        run: dotnet publish -c Release -o "${{ vars.PUBLISH_DIR }}"

      - name: Check publish
        run: ls "${{ vars.PUBLISH_DIR }}"

      - name: Archive Publish
        run: tar -czvf ./artifacts.tar.gz ./publish

      - name: Store publish
        uses: actions/upload-artifact@v4
        with:
          name: pubdata
          path: ./artifacts.tar.gz

      - name: End publish
        run: echo "${{ secrets.TEST_SECRET }}"

  release:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pubdata
          path: /tmp
      - name: Check Artifacts
        run: ls /tmp

      # copy file to server ...
